# Generated by Django 5.2.1 on 2025-05-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ikon', models.CharField(help_text='Font Awesome Icon Class', max_length=100)),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Kontak Saya',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('jabatan', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
            ],
            options={
                'verbose_name_plural': 'Profil Diri',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='project/')),
                ('link', models.URLField(blank=True, null=True)),
                ('stack_teknologi', models.CharField(help_text='Contoh: HTML, CSS, JS', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Projek ShowOff',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('deskripsi', models.TextField()),
                ('icon', models.CharField(help_text='Font Awesome Icon Class', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Layanan Website',
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimoni/')),
                ('jabatan', models.CharField(max_length=100)),
                ('testimoni', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Testimoni Klien',
            },
        ),
    ]
